stacks-network/docs

_browser/todo-list.md

Replace references to React with Vue.js

Replace React with Vue

---

_browser/todo-list.md

Correct the paths

---

_develop/mining_enroll.md

Adding mention of public/private in app mining'

---

_develop/zero_to_dapp_1.md
_develop/zero_to_dapp_2.md
_develop/zero_to_dapp_3.md
_develop/zero_to_dapp_3_win.md
_develop/zero_to_dapp_4.md

Some copy edits

---

_org/tokenholders.md

Clarify token availability

---

_develop/zero_to_dapp_4.md

Fixing the ruler

---

_develop/zero_to_dapp_4.md

- clarify the difference between submission and adding
- Break out submission procedure

Updating app mininig section

---

_includes/head.html

Tweaking head

---

_browser/hello-blockstack.md

Updating the text in hello blockstack tutorial to point to the correct filename for the javascript code.

Update filename in hello blockstack tutorial

---

_develop/zero_to_dapp_1.md
_develop/zero_to_dapp_3.md
_develop/zero_to_dapp_4.md

Updating to correct Gaia as a requirement

---

_data/navigation_org.yml
_org/tokenholders.md
_org/voucherholder.md

Update for voucher

---

_config.yml
_data/appFAQ.json
_data/navigation_learn.yml
_develop/appMiningFAQ.md
_develop/faq-data.json
_org/wallet-install.md

Setting up FAQs for app mining

---

_data/appFAQ.json

Fixing punctuation

---

_develop/zero_to_dapp_3.md

Tweaking to see how it impacts the funnel

---

_data/navigation_home.yml
_develop/zero_to_dapp_1.md
_develop/zero_to_dapp_2.md
_develop/zero_to_dapp_3.md
_org/overview.md

Fixing capitalization

---

_develop/zero_to_dapp_2.md

Fixing step alignment

---

_org/wallet-install.md

Tweaking per Ken and Thomas

---

_develop/zero_to_dapp_1.md
_develop/zero_to_dapp_3.md
_develop/zero_to_dapp_4.md

Several updates to Zero to DApp

Zero to dapp update

---

_develop/zero_to_dapp_4.md

Closes #92

---

_data/navigation_org.yml
_org/whitepaper-blockchain.md

Fixes #103 by adding technical white paper

---

_data/community.json
_data/navigation_learn.yml
_develop/communityResources.md

Starting work toward Issue #108 this a start

---

_core/naming/architecture.md
_core/naming/comparison.md
_core/naming/search.md
_develop/zero_to_dapp_2.md
_develop/zero_to_dapp_3.md

- Closes #105
- Thanks to @lizblockstack for the catches

Fixing assorted typos

---

_config.yml

Fixing the copyright Closes #116

---

_develop/mining_intro.md
_includes/intro-appmining.md
_includes/payout-appmining.md

Adding in Patricks comments

---

_browser/todo-list.md

Found while working through the tutorial while completing an interview project!

Fixes a newline and copypaste error in directory check

---

_data/navigation_home.yml
_develop/zero_to_dapp_1.md

Updating to direct to Zero-to-Dapp

---

_data/appFAQ.json

Fixes https://github.com/blockstack/app.co/issues/455

Fixes blockstack/app.co/issues/455

---

_browser/blockstack_storage.md

Fixing link to bad example

---

_develop/zero_to_dapp_3.md
_develop/zero_to_dapp_4.md
_storage/digital-ocean-deploy.md

Fixes https://github.com/blockstack/docs.blockstack/issues/139

Removing offending section per Patrick killin bad dashes

---

_develop/mining_intro.md

This PR
* adds a section about the app-mining github repo

Add link to app-mining github repo

---

_develop/zero_to_dapp_2.md
_develop/zero_to_dapp_2_win.md
_org/address_check.md
_org/faq.md

Updating FAQs for Freddy

---

_data/appFAQ.json
_develop/vote-blockstack.md

@paulamlb your requested fixes

Fixes for Democracy Earth

---

_browser/faq_general.md

Fixing typos

---

_browser/faq_general.md

Close #168

---

_config.yml

Fixing typo in decentralized

---

_data/community.json

See https://forum.blockstack.org/t/debugging-blockstack-react-app/7572/6 :)

Add craco-blockstack to the community links

---

_develop/zero_to_dapp_3.md
_develop/zero_to_dapp_3_win.md

Bad build instruction removed the step to run build after cores. 

Close #180 remove bad build instruction

---

_common/android_ref.md
_data/navigation_core.yml
_data/navigation_learn.yml
_data/navigation_storage.yml

This PR
* adds a link to the (generated) Android Reference documentation

Add Android API Reference

---

_develop/mining_intro.md
_layouts/community.html

App mining trymyui

---

_layouts/community.html

Updating with a fix

---

_data/glossary.csv

Add missing space to zone file definition

---

_develop/zero_to_dapp_3.md
_develop/zero_to_dapp_3_win.md
contact.md

Small typos caught by a reader.

Some typos caught by Pat Murphy

---

_layouts/community.html

fix community

---

_data/theFAQs.json

Additional last minute changes.

Updating with last minute things

---

_org/faq.md

updating stacks list

---

_data/theFAQs.json
_faqs/allFAQS.md
_org/faq.md

Updating with finals

---

_common/javascript_ref.md

short term fix to javascript

---

_common/javascript_ref.md

Return Javascript to Correct GH P Link

---

_data/theFAQs.json

Closes #216 New Stacks FAQ

---

_data/theFAQs.json

Add URL / domain qualification

---

_data/appFAQ.json

updating old stuff

---

_data/appFAQ.json

Fixing again --- copying again

---

_develop/storage.md

Adding in right way to use UserSession

---

_browser/todo-list.md

Todos now working with the right example for the json

Fixing the example

---

_browser/blockstack_storage.md

Updated storage tutorial to v19 API. 
Added link to updated source code and deployed live demo.

Update storage tutorial to blockstack.js v19 API

---

_data/appFAQ.json
_data/theFAQs.json

Updating FAQ requirements

---

_data/navigation_learn.yml
_develop/app-reviewers.md
_develop/mining_intro.md

Updating app-reviewers details

---

_data/theFAQs.json

Link to the Reg A in the FAQs 

---

_data/theFAQs.json
_layouts/org.html

Updating per Mitchell Fixes #247

---

_org/tokenholders.md
_org/voucherholder.md

Updating with links to the FAQS

---

_browser/todo-list.md

fixing typo

---

_data/theFAQs.json

Change will to may in the FAQ

---

_data/theFAQs.json

Updating the New York resident FAQ

---

_develop/auth_provider.md

This PR
* fixes the link to omniauth

Fix link to omniauth

---

_develop/auth_provider.md

Fixing tweet

---

_data/theFAQs.json

Fixes #267 Update to token FAQs

---

Gemfile
Gemfile.lock
_config.yml
_includes/head.html
_layouts/default.html

Adding Google Tag Manager

---

_data/theFAQs.json

Closes #273

---

_browser/hello-blockstack.md

Light updates to the `hello-blockstack` tutorial to match the current developer experience.

Updated hello-blockstack docs to match latest

---

_browser/hello-blockstack.md

Updating with some framing language

---

_data/appFAQ.json
_data/theFAQs.json

Closes #277 app mining change faq

---

_includes/search-hero.html
_includes/search.html

Updating with latest search script

---

_includes/search-hero.html
_includes/search.html

Fixing the content groups

---

_includes/head.html
_includes/keyphrase.md
_includes/search.html
assets/js/main.js
package-lock.json

- package-lock.json
- JS error fixes

Fix reported

---

_core/smart/overview.md

Fixing mis wording

---

_core/smart/sdk-quickstart.md

Last minute tweaks

---

_data/navigation_learn.yml
_develop/app-rankings.md
_develop/app-reviewers.md
_develop/mining_intro.md
_includes/mining-ranking.md

Updating the content in the pages

First pass of the new pages

---

_develop/zero_to_dapp_2.md
_develop/zero_to_dapp_2_win.md

Removing bad information from table

---

_data/theFAQs.json

Updating the manual date

---

_data/theFAQs.json

Latest updates

---

_data/theFAQs.json

Dedup FAQS

---

_org/wallet-install.md

Updating the downloaded file names

---

_develop/zero_to_dapp_4.md

Adding CTA to Fix #292

---

_data/theFAQs.json

Updating the faqs

---

_data/navigation_org.yml
_data/theFAQs.json
_org/wallet-troubleshoot.md

Updating the content on Wallet

---

_data/theFAQs.json

Tweak per Aaron

---

_data/theFAQs.json

Add more language around Texas etc.

Updating with new FAQ

---

_data/appFAQ.json
_data/theFAQs.json

Adding a sentence to rewards FAQ

---

_data/theFAQs.json
_develop/app-reviewers.md

Change request by @fjl4 and one by @GinaAbrams 

Updating with new changes

---

_data/theFAQs.json

Fixing exposed strong

---

_data/theFAQs.json

Adding in timestamp

---

_config.yml
_core/api-specs.md
_core/blockstack-did-spec.md
_core/naming/search.md
_core/subdomain.md
_core/wire-format.md

Comparison to core

---

_org/wallet-troubleshoot.md

Angelist login troubleshooting

New troubleshooting information

---

_develop/app-reviewers.md

Fixes https://github.com/blockstack/app-mining#102

Requests from App Mining team

---

_develop/zero_to_dapp_1.md

Remove signature fund reference from Z2D

---

_browser/local_browser.md

Fixing typo in wallet install

---

README.md
_core/smart/clarityRef.md
_data/clarityRef.json

Update of Clarity Reference

---

_core/naming/creationhowto.md

Remove links from the namespace creation

---

_data/clarityRef.json

Updating clarity reference

---

_core/naming/architecture.md

Closes #353 to fix alignment

---

_storage/amazon-s3-deploy.md

Tweak jwiley fix

---

_data/theFAQs.json

Updating FAQ regarding exchanges

---

_common/mining_faq.md

Removing outdated file

---

_develop/collections.md

Adding in Ken's comments

---

_android/tutorial.md
_browser/blockstack_storage.md
_browser/hello-blockstack.md
_browser/todo-list.md
_develop/zero_to_dapp_2.md
_develop/zero_to_dapp_2_win.md
_develop/zero_to_dapp_3.md
_develop/zero_to_dapp_3_win.md
_includes/scaffolding.md
_ios/tutorial.md
_storage/hello-hub-choice.md

Relates to #blockstack/blockstack-app-generator/pull/67

---

_browser/hello-blockstack.md

Updating with new app generation

---

_android/tutorial.md
_browser/blockstack_storage.md
_browser/hello-blockstack.md
_includes/scaffolding.md
_ios/tutorial.md

Clean up of tutorials after work on app-generator

---

_org/tokenholders.md

Fixes #378 for hard folk allocation checker

---

_org/wallet-install.md
_org/wallet-use.md

Removing Model T until we can resolve issue

---

_develop/app-reviewers.md

Fixes #396 update TryMyUI text

---

_develop/app-reviewers.md

Reverts blockstack/docs.blockstack#401

Revert "Awario fixes"

---

_develop/app-reviewers.md

Fixes #339

---

_data/theFAQs.json
_faqs/allFAQS.md

Updates 10/17

---

_data/theFAQs.json

Grammar check

---

_develop/collections.md

Removed custom Gaia hub setup steps and added the collections test page for viewing of contacts data.

Update collections preview docs

---

_develop/dapp_principles.md

I corrected several minor errors and made a few other suggested edits.

Corrections/optimizations to dapp_principles.md

---

_core/smart/clarityCLI.md
_core/smart/functions.md
_core/smart/overview.md
_core/smart/principals.md
_core/smart/sdk-quickstart.md
_core/smart/tutorial.md
_org/wallet-install.md

Reverts blockstack/docs.blockstack#412

Revert "Updates clarity and tweek wallet link"

---

_core/smart/clarityCLI.md
_core/smart/overview.md
_core/smart/sdk-quickstart.md
_core/smart/tutorial.md
_org/wallet-install.md

* Explicit step to go to download page for wallet per 
* Clarify the `clarity-cli` for the VM and `clarity` for the SDK

Clarity cli fix and wallet update

---

_data/theFAQs.json

Changing the amount per freddie

---

_data/theFAQs.json

Updating company name

---

_data/theFAQs.json

matching last fix date to history

---

_data/community.json

Adds a KubeSail button https://github.com/blockstack/gaia/pull/257

Closes blockstack/gaia/pull#257

---

_ios/tutorial.md

Putting in a link to the photo app

---

_ios/tutorial.md

Correcting capitalization of signIn

---

_develop/app-reviewers.md
_includes/note-list.html

Closes #684 and updates the notes for app mining reviewers

---

_org/wallet-install.md
_org/wallet-use.md

Updating with note

---

_data/appFAQ.json
_data/theFAQs.json
_develop/mining-rewards.md
_includes/intro-appmining.md

Updating with new  FAQs

---

_data/navigation_learn.yml
_develop/deploy-tips.md

Fixes #32 for deploying an app

---

_develop/deploy-tips.md
_develop/profiles.md

- Removing references to social proofs that are no longer supported
- Adding in Reeds comments to the deploy app

1201 updates from pull requests

---

_develop/app-reviewers.md

Updates per @GinaAbrams Closes #455

---

_develop/mining-rewards.md

updating to 30K

---

_storage/config-schema.md

Updating the configuration reference

---

_data/navigation_learn.yml
_develop/collection-type.md
_includes/question.html

Updating with Collection new type doc

---

_develop/collection-type.md

Missing a commit

---

_data/navigation_learn.yml
_develop/overview_auth.md
_develop/radiks-collaborate.md
_develop/radiks-intro.md
_develop/radiks-models.md
_develop/radiks-server-extras.md
_develop/radiks-setup.md
_develop/storage.md
_develop/zero_to_dapp_2.md
_develop/zero_to_dapp_2_win.md
_develop/zero_to_dapp_3.md
_develop/zero_to_dapp_3_win.md
_includes/architecture.md
_includes/commandline.md
_includes/question.html
_org/wallet-install.md
_storage/overview.md

Adding radiks to the docs

---

_develop/radiks-server-extras.md

- streaming and centralized stores

Adding in some updates

---

_develop/mining_enroll.md

Reverts blockstack/docs.blockstack#513

Revert "Update mining_enroll.md"

---

_org/explore.md

Changed Graphite.it to naval.id

Updated a typo

---

_storage/digital-ocean-deploy.md

Initial/minimal updates to docs for upcoming [concurrency control changes](https://github.com/blockstack/gaia/pull/276/) in Gaia
@moxiegirl feel free to close this and open a proper PR with better wording, etc. Just wanted to supply this as reference

update digital ocean docs for concurrency changes

---

_core/smart/cli-wallet-quickstart.md

Fixes the commands for testnet CLI wallet, adding the correct ports.

Specify CLI wallet testnet URL ports

---

_core/smart/cli-wallet-quickstart.md

Fixes fee rate in the CLI wallet example so that the transaction will actually get accepted.

fix: update cli wallet transaction fee rate.

---

_core/smart/overview.md
_core/smart/principals.md
_core/smart/tutorial-counter.md
_core/smart/tutorial.md
_develop/connect/get-started.md
_develop/connect/overview.md
_develop/connect/use-with-clarity.md
_develop/profiles.md

Will wait for input from @jcnelson on:
- Principals language
- Movie catalog example

Incorporate feedback from Mark

---

Gemfile
Gemfile.lock
_core/smart/neon-node.md

Includes updates for https://github.com/blockstack/stacks-blockchain/pull/1502

Node guide: Add debug info & linux requiremen, remove ruby version for local installation

---

_develop/radiks-intro.md

I wasn't sure how to make the last sentence on line 32 more clear, since at the beginning of the paragraph it says that all data is encrypted before being sent to a Radiks server, but the last sentence implies that some data on the Radiks server is unencrypted (or else no queries would be returned)

Make Radiks Intro doc more readable

---

_develop/radiks-collaborate.md

This PR
* add documentation for generic invitations for radiks that is introduced in https://github.com/blockstack/radiks/pull/72

Add documentation for generic invitations for radiks

---

_core/smart/overview.md

Simplified contract examples and changed some prose / wording

Changes to Clarity Overview

---

_common/core_ref.md

It is understood that we need to think through how we are going to educate developers on what they should use (Rust RPC vs Sidecar). I wanted to take a stab at a _first_ iteration that will hopefully make a first step in the right direction.

Update stacks node api docs

---

_develop/radiks-intro.md

I found it when translate.
I fix it similar to other part, Radiks.

fix typo for Radiks

---

_core/smart/sdk-quickstart.md
_core/smart/tutorial-counter.md
_core/smart/tutorial.md

Fix: Small updates to clarity tutorials

---

_ios/tutorial.md

Small fixes/updates to the iOS SDK tutorial to go along with authenticator update.

Updates for iOS SDK tutorial

---

develop/connect/use-with-clarity.md

feat: check tx status

---

src/common/utils/index.ts
src/components/mdx/components/heading.tsx
src/components/side-nav.tsx
src/pages/references/faqs/[slug].tsx

resolves https://github.com/blockstack/docs/issues/727

fix: id for faqs

---

src/pages/smart-contracts/counter-tutorial.md

Fixed some indentation, typos, and phrasing after watching a developer test

fix: minor changes to counter tutorial

---

src/includes/different_apis.md
src/pages/references/stacks-blockchain.md

Adding client lib info, related to this PR: https://github.com/blockstack/stacks-blockchain-api/pull/202

feat: add info about api client lib

---

src/pages/stacks-wallet/usage.md

docs: add trezor support content

---

src/pages/stacks-wallet/usage.md

Update wallet instructions on transitioning from Trezor to Ledger

Update wallet usage instructions

---

src/pages/stacks-blockchain/running-testnet-node.md

improvement: running testnet instructions

---

src/pages/stacks-blockchain/accounts.md

This adds a reference to [stacks-gen](https://github.com/psq/stacks-gen) to the accounts creation page

feat: add stacks-gen

---

src/_data/boot-contracts-reference.json
src/common/data/stacking-ref.ts
src/common/navigation.yaml
src/components/stacking-ref.tsx
src/pages/references/stacking-contract.md
src/pages/stacks-blockchain/stacking.md

fixing #812
in reference to: https://github.com/blockstack/stacks-blockchain/pull/1957/

feat: add stacking reference page

---

src/pages/stacks-blockchain/overview.md

Changed around some wording/phrasing. Tried to make it more comprehensible and consistent with our other messaging.

Fixes to Stacks Blockchain Overview

---

src/pages/authentication/building-todo-app.md
src/pages/authentication/connect.md
src/pages/references/blockstack-cli.md
src/pages/smart-contracts/cli-wallet-quickstart.md
src/pages/smart-contracts/hello-world-tutorial.md
src/pages/stacks-blockchain/accounts.md
src/pages/stacks-blockchain/managing-accounts.md
src/pages/stacks-blockchain/network.md
src/pages/stacks-blockchain/sending-tokens.md
src/pages/stacks-blockchain/transactions.md

Auth and tutorial updates for the new @stacks NPM packages.

feat: auth tutorial updates for stacks.js

---

src/common/navigation.yaml
src/pages/authentication/building-todo-app.md
src/pages/authentication/overview.md
src/pages/data-storage/overview.md
src/pages/data-storage/storage-guide.md
src/pages/data-storage/storage-write-read.md
src/pages/naming-services/architecture.md
src/pages/naming-services/subdomains-tutorial.md

This PR updates the link to blockstack.js reference docs to stacks.js.

fix links for stacks.js reference docs

---

src/pages/ecosystem/contributing.md

As a contributor I would like to just work in the browser without a local setup.
This is possible with gitpod. 
No
No
View the newly build docs

Add gitpod link

---

src/pages/references/stacks-node-configuration.md

Updating the description of some config options.

docs: update some descriptions

---

src/pages/stacks-blockchain/accounts.md
src/pages/stacks-blockchain/integrate-stacking.md
src/pages/stacks-blockchain/stacking.md

docs: adding info for bitcoin address

---

src/common/data/clarity-ref.ts

This PR sorts the functions and keywords list by name, the content is sorted in the same way.
For details refer to issue #744 
**Before**
**After**
No
No
No

feat: alphabetize functions and keywords lists #744

---

src/pages/ecosystem/contributing.md

For details see "Adding a new route" #847
This PR removes references to `all-routes.json` and explains how to add a route to `navigation.yaml`.

fix: explain how to add routes to navigation

---

src/pages/stacks-blockchain/stacking.md

docs: fix format

---

src/pages/smart-contracts/public-registry-tutorial.md

The referenced smart contract id in the public registry tutorial might change over the time.
This PR 
* updates the section describing how to find and deploy the contract if need.
* fixes #910

fix: explain how to find the contract #910

---

src/pages/stacks-blockchain/integrate-stacking.md

Updates calculation with changes to accurately calculate blocks remaining in cycle

fix: stacking block calc

---

.github/workflows/main.yml

This fixes the broken GH actions.

fix: gh action setup-node

---

src/pages/storage-hubs/amazon-ec2-deploy.md
src/pages/storage-hubs/digital-ocean-deploy.md

@agraebe, could you take a look at this suggested link fix? Not sure if this is the correct approach, or what I may have missed. 🙏 
I was looking at the docs tooling and organization and found a broken link. Thought I'd make a quick PR to fix it. I reviewed the  contributor README and the navigation.yaml, but didn't take the time to test by installing npm, yarn, and other dependencies, so this is just a guess to the correct syntax for the link.
As mentioned, **I did not test this change**, so _maybe_?

Adds untested link fix; clarifies language for similar link.

---

src/components/mdx/image.tsx

This removes the staging env variable to allow for deployments to work automatically

fix: remove staging env

---

next.config.js

Adds in some redirects to fix broken links.
Closes https://github.com/blockstack/docs/issues/949

fix: add redirects for mining and stacking pages

---

next.config.js

redirects required after these changes were rolled out: https://github.com/blockstack/docs/pull/885/files

Adding missing redirects from top lvl chapter change

---

src/pages/understand-stacks/running-testnet-node.md

add mining hardware info

---

src/pages/understand-stacks/integrate-stacking.md

This PR updates the stacking integration guide to use the new stacking lib https://github.com/blockstack/stacks.js/pull/850

feat: new stacking integration guide using stacking lib

---

README.md
src/pages/ecosystem/contributing.md
src/pages/write-smart-contracts/public-registry-tutorial.md

This pr aims to remedy issue https://github.com/blockstack/docs/issues/950. I don't think the bounty links live in this repo so I omitted them.
No
No
- Check out the ecosystem page and the public registry tutorial

Fix Incorrect links

---

src/pages/start-mining.md

docs: fix port typo

---

next.config.js
src/pages/ecosystem/stacks-token.md

docs: fix old url

---

src/pages/understand-stacks/mining.md

As someone who wants to learn more about blockstack and never made a change in open source code. I wanted to fix a typo I found to clean up the docs. Minig to Mining
No
No
N/A
N/A

Fix a typo in docs

---

.github/PULL_REQUEST_TEMPLATE.md

Add template discussed in issue https://github.com/blockstack/docs/issues/959.

Add new pull request template

---

src/pages/references/language-types.md

Add UTF-8 string example based on https://github.com/blockstack/docs/issues/944.

Add UTF-8 string example

---

src/pages/understand-stacks/accounts.md
src/pages/understand-stacks/integrate-stacking.md
src/pages/understand-stacks/network.md
src/pages/understand-stacks/overview.md
src/pages/understand-stacks/proof-of-transfer.md
src/pages/understand-stacks/transactions.md

Update Stacks overview page

---

README.md
next.config.js
package.json
src/_data/cli-reference.json
src/common/navigation.yaml
src/pages/ecosystem/contributing.md
src/pages/references/stacks-cli.md
src/pages/start-mining.md
src/pages/understand-stacks/accounts.md
src/pages/write-smart-contracts/cli-wallet-quickstart.md
src/pages/write-smart-contracts/hello-world-tutorial.md

Fixing CLI references

---

src/common/constants.ts
src/components/common.tsx
src/components/header.tsx
src/components/home/common.tsx
src/components/layouts/base-layout.tsx

feat: full-width docs

---

src/pages/understand-stacks/technical-specs.md

Minor updates to technical specs.

---

src/pages/storage-hubs/amazon-ec2-deploy.md
src/pages/understand-stacks/integrate-stacking.md
src/pages/understand-stacks/network.md
src/pages/understand-stacks/running-testnet-node.md
src/pages/understand-stacks/stacking-using-CLI.md
src/pages/understand-stacks/transactions.md
src/pages/write-smart-contracts/public-registry-tutorial.md

docs: update broken urls, fix small code sample inconsistency

---

src/pages/understand-stacks/stacking.md

docs: update token holder eligibility info

---

src/pages/references/stacking-contract.md

docs: update contract id info

---

src/pages/authentication/building-todo-app.md

See typo, fix typo :)
• Fix a couple of typos
• Update "unauthenticate" to "deauthenticate" to match usage later in the doc
None

docs: correct minor typos in todo app docs

---

src/pages/understand-stacks/sending-tokens.md

docs: fix code samples

---

src/pages/understand-stacks/integrate-stacking.md

docs: fix stacking code sample

---

src/pages/references/stacks-node-configuration.md

- add warning to `working_dir`
- add `satoshis_per_byte` and note about total transaction cost
- remove `burnchain_op_tx_fee`

Update stacks-node configuration option docs.

---

src/pages/build-apps/guides/authentication.md
src/pages/build-apps/guides/data-storage.md
src/pages/build-apps/guides/transaction-signing.md
src/pages/build-apps/tutorials/angular.md
src/pages/index.md
src/pages/understand-stacks/overview.md

Improves and fixes a few details related to https://github.com/blockstack/docs/pull/1014.

Improve and fix miscellanea for "Build apps" section

---

src/pages/build-apps/tutorials/public-registry.md
src/pages/understand-stacks/accounts.md
src/pages/understand-stacks/command-line-interface.md
src/pages/understand-stacks/integrate-stacking.md
src/pages/understand-stacks/managing-accounts.md
src/pages/understand-stacks/network.md
src/pages/understand-stacks/overview.md
src/pages/understand-stacks/sending-tokens.md
src/pages/understand-stacks/stacking-using-CLI.md
src/pages/understand-stacks/stacks-blockchain-api.md
src/pages/understand-stacks/transactions.md
src/pages/write-smart-contracts/counter-tutorial.md
src/pages/write-smart-contracts/hello-world-tutorial.md
src/pages/write-smart-contracts/values.md

should solve _some_ issues from #835

chore: update mainnet urls

---

src/pages/understand-stacks/overview.md
src/pages/understand-stacks/testnet.md

feat: mainnet content updates

---

src/pages/build-apps/tutorials/public-registry.md

The file name was incorrect, and the sentence structure could be written more directly to describe the action of creating a file in a directory.
I changed the filename and the sentence structure of a sentence in `public-registry.md` file.
None.

fix: filename extension and sentence structure

---

src/_data/boot-contracts-reference.json
src/common/data/bns-ref.ts
src/common/navigation.yaml
src/components/bns-ref.tsx
src/pages/references/bns-contract.md

fixes #1006 
related PR for reference generation: https://github.com/blockstack/stacks-blockchain/pull/2310

docs: add bns references

---

src/pages/understand-stacks/integrate-stacking.md
src/pages/understand-stacks/network.md
src/pages/understand-stacks/stacking.md

docs: update stacking delegation info

---

src/pages/understand-stacks/technical-specs.md

docs: add mempool info

---

src/pages/understand-stacks/managing-accounts.md

Wrap await in async function in "Step 3: Reviewing account info"

fix: Wrap await in async function

---

src/_data/boot-contracts-reference.json

Fix mentioned in https://github.com/blockstack/docs/pull/1067#issuecomment-774782960

fix: update refs with bns

---

src/pages/understand-stacks/command-line-interface.md

Updated typo

---

src/pages/understand-stacks/stacks-blockchain-api.md
src/pages/understand-stacks/technical-specs.md
src/pages/understand-stacks/transactions.md

docs: fix SIP urls

---

src/pages/write-smart-contracts/hello-world-tutorial.md

fix: cli command for contract call

---

src/pages/build-apps/guides/transaction-signing.md

This PR adds docs to the transaction signing page to show details of the low-level interface for making transaction signing requests.
I'm mainly adding these docs for future wallet developers, and other developers who want to understand the lower-level protocol.
cc @yknl and @pradel - obviously the goal is to have multiple wallets that support transaction signing in an integrated web browser. This may not be the best place to debate the specifics of the implementation, but I'd love to start that conversation.

feat: add docs for transaction request payloads

---

src/pages/understand-stacks/running-mainnet-node.md
src/pages/understand-stacks/running-testnet-node.md

Adds ENV VAR section to target specific commits, versions, branches.
- [x ] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [x ] [Style guide](https://developers.google.com/style) was reviewed and applied

docs(testnet-node): Add section on ENV vars

---

src/pages/write-smart-contracts/hello-world-tutorial.md

fix: fix typo

---

src/pages/understand-stacks/technical-specs.md

fixing #1119
from https://github.com/blockstack/stacks.js/blob/master/packages/transactions/src/constants.ts#L16

Fixes blockstack/docs#1119

---

src/pages/understand-stacks/network.md

fix: nonce info

---

src/pages/understand-stacks/local-development.md

This PR
* removes references to bitcoin settings and to explorer. Explorer does not support local development very well.
* fixes #1104

Update stacks-local-dev documentation

---

src/pages/understand-stacks/overview.md

do clarity smart contracts get put on the bitcoin blockchain or on the stacks chain?

ambigious use of the word blockchain

---

src/pages/understand-stacks/technical-specs.md

Learn more about this PR <small>[here](https://github.com/blockstack/docs/pull/1132)</small>

fix: bad link descriptions

---

src/pages/understand-stacks/transactions.md

docs: fix content type

---

src/pages/start-mining/mainnet.md
src/pages/start-mining/testnet.md

Updates stacks-node miner configuration to use stacks.co domain name and improve sync times.

docs: update stacks-node mining configs

---

.gitignore

Adding the vscode project specific settings folder to the gitignore

chore: added .vscode directory to gitignore

---

src/common/navigation.yaml

This PR adds links to the current Stacks.js packages to the navigation sidebar. Additionally it adds a link to the migration guide from Blockstack.js -> Stacks.js

chore: added Stacks.js links to Build Apps section

---

src/pages/understand-stacks/transactions.md

This PR adds a mildly edited version of @diwakergupta's forum post on mempool and best practices to the Transactions page.  Original content [here](https://forum.stacks.org/t/transactions-in-mempool-best-practices-and-known-issues/11659).

feat: added mempool info from Diwakers forum post

---

src/common/navigation.yaml
src/pages/understand-stacks/local-development.md
src/pages/understand-stacks/running-api-node.md

This PR adds an article on running an API node locally.
This PR closes #1162

docs: added article on running an API node

---

src/pages/write-smart-contracts/clarinet.md

This PR fixes a few links on the Clarinet page.

chore: updated land fixed links on Clarinet page

---

src/pages/build-apps/examples/heystack.md

This PR addresses feedback provided by @andresgalante on the Heystack example application.

docs: addressed reviewer comments in Heystack example

---

.vale/styles/Google/Spacing.yml
.vale/styles/Google/WordList.yml
.vale/styles/Vocab/docs/accept.txt

Update the Google style rules to the latest release.

chore: update the Google style rules to latest release

---

src/pages/understand-stacks/overview.md

This PR adds a link to Jude's `What kind of blockchain is Stacks?` blog post to the [Understand Stacks](https://docs.stacks.co/understand-stacks/overview) page.

docs: added a link to Jthe What kind of blockchain is Stacks? post

---

src/common/navigation.yaml
src/pages/understand-stacks/command-line-interface.md
src/pages/understand-stacks/mining.md
src/pages/understand-stacks/stacking.md
src/pages/understand-stacks/stacks-blockchain-api.md

fix: linter error

---

src/pages/understand-stacks/microblocks.md

This PR integrates feedback from Diwaker on microblocks confirmation.

fix: implement feedback on microblocks confirmation

---

src/_data/clarity-reference.json

This reverts commit b5600ab447a75fe8c25f086919b2816ad1686cc0.
This was merged accidentally, the change needs to be made in `blockstack/stacks-blockchain`.

Revert "Update clarity-reference.json"

---

src/pages/understand-stacks/local-development.md

Updates some out-of-date info on the local-development page.

docs: update old info for local-development page

---

src/pages/understand-stacks/sending-tokens.md

Docs fix for https://github.com/blockstack/stacks.js/issues/1063

fix: update broadcastTransaction response

---

src/pages/write-smart-contracts/clarinet.md

This PR updates the documentation to the latest installation instructions for Clarinet.

docs: update Clarinet install instructions to include package managers

---

src/pages/understand-stacks/command-line-interface.md

Fix misspelling of "blockchain"

Fix mispelling

---

src/pages/write-smart-contracts/clarinet.md

Should be `Devnet.toml` instead of `Development.toml`

Fix Devnet.toml reference

---

src/pages/build-apps/guides/transaction-signing.md

Per https://forum.stacks.org/t/mempool-congestion-on-stacks-observations-and-next-steps-from-hiro/12325/5

Add fee parameter to transaction signing guide

---

src/pages/understand-stacks/transactions.md

Just stumbled upon this while reading the documentation

Remove unneeded code

---

src/common/navigation.yaml

Fixed the broken Write Smart Contracts link so that users can navigate to that content again.

fix: fixed broken write smart contracts section

---

src/pages/index.md

Revert "removed duplicate file"

---

src/pages/understand-stacks/running-mainnet-node/index.md

Added optional documentation on how to run a stacks node using your own bitcoin node.

stacks node with own btc node

---

next.config.js
src/common/navigation.yaml
src/pages/references/stacks-node-configuration/index.md

Updated docs and fixed broken links

Fix: Updated broken links

---

src/pages/understand-stacks/accounts/index.md

Updated output to the new stacks cli format

stacks cli update

---

src/pages/en/contributing.md

Updated new repositories and updated console log

contributing.md

---

next.config.js

The functions page was recently moved in #1318. This PR creates a redirect for this page.

Added a redirect for the functions page movement

---

package.json

Fixes [issue 1321](https://github.com/stacks-network/docs/issues/1321)

fixed issue #1321

---

crowdin.yml
src/pages/en/start-mining/mainnet.md

Crowdin config and small fix

---

src/components/feedback.tsx

Fixes [issue 1303](https://github.com/stacks-network/docs/issues/1303)

fixed feedback component

---

src/pages/en/understand-stacks/accounts.md

I try the original code and it doesn't work.
Add required info to import
---
Continue this PR https://github.com/stacks-network/docs/pull/1291

Fix missing code in accounts.md

---

src/pages/en/understand-stacks/proof-of-transfer.md

"Additionally, By" => "Additionally, by"

Fix grammar in proof-of-transfer.md

---

next.config.js
package.json
src/components/custom-blocks/page-reference.tsx
src/components/lazy-image.tsx
src/components/mdx/components/code.tsx
src/components/typography.tsx
src/pages/en/contribute/docs.md
tsconfig.json
yarn.lock

The `yarn` command had and output of:
```
yarn install v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @docsearch/react@1.0.0-alpha.28" has incorrect peer dependency "react@^16.8.0".
warning " > @docsearch/react@1.0.0-alpha.28" has incorrect peer dependency "react-dom@^16.8.0".
warning " > @emotion/babel-plugin@11.1.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/babel-plugin > @babel/plugin-syntax-jsx@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @emotion/babel-preset-css-prop@11.0.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/babel-preset-css-prop > @babel/plugin-transform-react-jsx@7.12.7" has unmet peer dependency …
```

fix: dependencies

---

README.md

removed Vale instructions and added icons

removed Vale instructions and added icons

---

next.config.js
src/pages/en/nodes-and-miners/miner-testnet.md
src/pages/en/nodes-and-miners/running-testnet-node.md
src/pages/en/nodes-and-miners/stacks-node-configuration.md

Issue 1275 - Running a testnet node

---

.eslintignore
.prettierignore

added list of translated files that need to get ignored by prettier and eslint

translations ignored files

---

next.config.js

Remove experimental features for increased stability

removed experimental features on next.config.js

---

src/pages/en/build-apps/deploy-tips.md

Small markdown fix on deploy tips that could be causing issue on translations

deploy tips

---

src/components/header.tsx

This PR will active the Indonesian language from the top right menu.
Should only get merged after [Issue 1373](https://github.com/stacks-network/docs/issues/1373) is resolved

activate indonesian language

---

src/pages/en/nodes-and-miners/digitalocean.md

Further details of the digitalocean droplet

DigitalOcean2

---

.github/labeler.yml
.github/workflows/label.yml

Added automatic action that can label PR automatically.

added automatic labeler

---

src/components/header.tsx

removing Spanish and Indonesian languages from the menu until issues are fixed

removing languages till issues are fixed

---

.github/workflows/auto-approve-translations.yml

Auto approve translations for that come in from Crowdin

Auto approve translations

---

src/pages/en/build-apps/nocodeclarity.md

updated nocodeclarity instructions pdf link

---

src/_data/glossary.csv

fixed glossary

---

docs/write-smart-contracts/clarity-language/language-functions.md

Fixed some functions that appeared as examples of the function above instead of their own ones.

clarity functions

---

docs/contribute/docs.md

fix contribute docs tree

---

docs/understand-stacks/accounts.md

fix issue 1475

---

docs/nodes-and-miners/running-testnet-node.md

Describe the changes that were made in this pull request. When possible start with the motivations behind the change.

markdown syntax correction

---

docs/write-smart-contracts/clarity-language/language-functions.md

fix: issue 1491

---

package-lock.json
package.json

Upgrade to docusaurus 2.0.1
Closes #1493

feat: docusaurus upgrade to stable version

---

package-lock.json
tailwind.config.js

As mentioned [here](https://github.com/facebook/docusaurus/issues/6631#issuecomment-1033557483), Docusaurus (or at least some packages inside) have an issue with M1 macs. I have added the suggested `tailwind.config.js` to the project's root to resolve.

Mac M1 Fix

---

docusaurus.config.js

fix: issue 1473

---

src/components/HomepageFeatures/reportWebVitals.js

Vercel Analytics

---

src/components/HomepageFeatures/reportWebVitals.js

Describe the changes that were made in this pull request. When possible start with the motivations behind the change.

AnalyticsID

---

docs/gaia/gaia.md

GAIA whitepaper

---

docs/governance/index.md
docs/governance/sips.md

Added governance and SIPs information

Governance

---

docs/contribute/docs.md
docs/governance/index.md
docs/governance/sips.md

SIP community calls

---

docs/understand-stacks/stacks-blockchain-api.md

Crowdin deleted file bug workaround

Crowdin deleted file bug workaround

---

docusaurus.config.js

added redirect for stacks-blockchain-api

added redirect for stacks-blockchain-api

---

docusaurus.config.js

restore link check

---

docs/governance/sips.md

Added SIP 16

---

docs/blockchain/stacks-releases.md

Stacks 2.1 information

---

docs/write-smart-contracts/index.md

Missing bulletpoints

---

README.md
docs/tutorials/satoshis-ridge.md

Fix: typos

---

docs/clarity/security/decidable.md

Just made a basic polishing pass.
Split some sentences into smaller sentences.
Tweaked a few words

minor polishing

---

clarity/functions.md

Fixes bad formatting on the functions page. See issue #1604 .

fix function formatting part 2

---

nakamoto-upgrade/nakamoto-in-10-minutes.md

fix: More accurate explanation of the updated leader block commit

---

nakamoto-upgrade/signing-and-stacking/running-a-signer.md
nakamoto-upgrade/signing-and-stacking/sample-configuration-files.md

Fixed grammar in one sentence and fixed the `-v` flag in the docker run command.

fix: minor tweaks to the signer docs

---

stacks-101/accounts.md
stacks-101/api.md
stacks-101/network.md
stacks-101/testnet.md
stacks-in-depth/nodes-and-miners/mine-testnet-stacks-tokens.md

Minor fixes:
- adjust FQDN for the Hiro testnet API
- adjust tesnet bootstrap node in non-nakamoto docs

update ports and fqdn

---

nakamoto-upgrade/signing-and-stacking/stacking-flow.md

Updating the wording around this parameter explanation after a discussion on Discord.

docs: clarify explanation of `start-burn-ht`
