- _browser/todo-list.md
We can use npm instead of yarn.
While yarn may be preferable for advanced users, it does create an additional external dependency.  For a beginner tutorial, I suggest npm is preferable.
Modern npm has lockfile capability and is arguably as performant as yarn now.
> Use npm instead of yarn

- _config.yml
- Make sure the _data directory served only contains the data we want to share.
> Reducing what is pushed from data directory

- _data/appFAQ.json
This PR
* adds a sentence about which apps are not eligable
* fixes a typo
* adds links to the details of the current reviewers and the app-mining github repo
> Improve app mining FAQ

- _includes/payout-appmining.md
This PR
* removes a duplicate phrase in the section about app mining payouts.
> Remove duplicate phrase in app mining payouts

- assets/js/main.js
Offset was false causing the links to hit the wrong place.
> Fix offset

- _data/theFAQs.json
Translation caught two typos. This corrects them.
> Fixing typo and omission found by translator

- _browser/blockstack_storage.md
For example, the setting to allow dots in the url is enabled by default by create-react-app, and the BrowserRouter component is already in the src/index.js file.  (Only relevant after the React app generator changes have been approved)
> Deleted steps in storage tutorial made redundant by new React App Generator

- _browser/blockstack_storage.md
Any app can use Gaia, but (only) those that need to share it publicly should request the scope.
> **Every app that uses Gaia storage must add itself** to the user's profile.json file.
to
> **Any Blockstack app can use Gaia storage, but those apps that need to share data publicly must add themselves** to the user's profile.json file.
>  Clarify `publish_app` scope 

- collections.json
The "_browser" folder will be update twice in the "get_content.sh" script.
- The first "name" and "repo" is correct, the svn will download file from right repo address 
- But the second is wrong, it will delete the "right" _browser folder and create a new one with android repo's source
This will lead to the browser page not found. (From i tried)
It is simple to figure out, i think i don't need to put any picture here.
> fix content->browser bug

- _includes/create_id.md
This PR
* adds a sentences about the format restrictions for new usernames in the blockstack browser
* fixes #363
> Add format restrictions for new ids

- _faqs/allFAQS.md
Search 360 provides the ability to use a FAQ page we and make every single Q&A block easily searchable (vs resorting to the CTRL+F shortcut to find the information within the page). This means just the FAQ topic returns in the search.
> Implement FAQ specific search

- _develop/betatesting.md
Changed
> Once beta mode is engaged, your local Blockstack redirects all activity to a hosted version of Blockstack at `beta.browser.blockstack.org`. You'll have to sign in with your Blockstack ID again to the **best** code.
to
> Once beta mode is engaged, your local Blockstack redirects all activity to a hosted version of Blockstack at `beta.browser.blockstack.org`. You'll have to sign in with your Blockstack ID again to the **beta** code.
> Changed "best code" to "beta code" in betatesting

- _develop/radiks-intro.md
This PR
* adds a missing `td` tag in the radiks intro file for developers
> Add missing td end tag in radiks intro

- _storage/write-to-read.md
This PR
* adds a paragraph to `Address-based access-control` section about how to read (public) data.
* fixes #344 (using banter.pub here instead of publik due to server certificate problems)
> Add details about how to do reads

- _core/smart/cli-wallet-quickstart.md
This adds a quickstart guide for the CLI wallet with instructions specific to Testnet. The guide will show developers how to install the CLI, create a wallet, receive tokens from the faucet and send tokens out from their account.
The guide can be found under Build Smart Contracts -> References
> CLI wallet quickstart

- _core/smart/neon-node.md
The blockchain now has default configuration for Neon nodes. There is also a streamlined binary, where you can more easily run a node of any type.
> docs: streamlined neon node

- _browser/hello-blockstack.md
The old URLs will redirect to the Hello, Blockstack tutorial (https://docs.blockstack.org/browser/hello-blockstack.html)
> add redirects for zero to dapp URLs

- _core/smart/functions.md
Under define and define-public functions in the table when foo.A returns ok the value for Data impact that results
mentions foo.B which was not previously mentioned.
> foo.B -> bar.B

- _develop/radiks-setup.md
The default MongoDB URI for radiks should start with `mongodb` rather than `MongoDB`, following the [standard connecting string format](https://docs.mongodb.com/manual/reference/connection-string/#connections-standard-connection-string-format)
> Update default mongodb uri

- _core/smart/neon-node.md
Added to the `neon-node` page for how to run a miner.
**Blockers**:
- We need this merged and deployed: https://github.com/blockstack/stacks-blockchain-sidecar/pull/92
- We need the testnet website updated with the BTC faucet form. Right now, that's staged at https://testnet-staging.blockstack.org/faucet
> feat: add docs for mining

- _develop/cliDocs.md
Changes `blockstack_cli` to "Blockstack CLI" in nav.
> Fix Blockstack CLI title in navigation

- _develop/connect/get-started.md
Docs for handling authentication if the `postMessage` flow fails - which can happen on mobile.
> feat: docs for handling redirect with connect

- _core/smart/cli-wallet-quickstart.md
Updates to the simplified commands recently pushed to the Stacks 2.0 CLI PR. Node URL no longer needs to be specified when using the `-t` flag.
> Update CLI wallet quickstart, simplifying commands

- _core/smart/neon-node.md
This PR
* uses `testnet/stacks-node` instead of `testnet` to build a release of stacks-node
> [smart] Use correct folder for stacks-node

- _core/smart/principals.md
This adds a couple example contracts and additional explanation to the principals page for `tx-sender` and `contract-caller`, showing how they can be used to enforce two different authorization schemes. This also shows an example usage of `as-contract` for managing a contract-owned asset.
> Add examples for principal keywords, as-contract

- _core/smart/neon-node.md
- _core/smart/testnet-node.md
This PR does the following:
- Updates miner conf's `bootstrap_node` to use the stable domain `testnet-master.blockstack.org`, which shouldn't change during later testnet phases.
- Updates miner conf's `mode` and `peer_host` for argon.
- Updated any CLI commands to use `argon` instead of `neon`, i.e. `stacks-node argon`.
- Removed any reference to "Neon network", and replaced it with more generic language like "testnet network".
> feat: update node docs for argon

- _develop/connect/use-with-clarity.md
We now have the full Connect transaction signing flow for the three TX types:
- contract call
- contract deploy
- stx transfer
This PR updates the Connect docs for this stuff, and does some clean up / improvement on the existing docs.
> feat: connect tx signing docs

- core/smart/tutorial.md
This PR
* replaces `debug/faucet` with `faucet/stx`
> Use correct faucet url

- develop/connect/overview.md
The guidance given here for `sendToSignIn` seem to be backwards in that it should be `true` to send the user through the sign in flow.
> Fix sendToSignIn guidance

- develop/connect/use-with-clarity.md
This removes the special configuration for using transaction signing since we're merging this functionality into master. It also adds guidance about its usage on testnet.
> Update transaction signing docs for testnet release

- src/components/side-nav.tsx
- src/components/status-check.tsx
This adds a status checker above the left side navigation. Outstanding for this PR would be:
> feat: next with status check

- src/pages/mining.md
Current miner config is using the older `argon.blockstack.org` DNS entry, which isn't able to track external IPs for http://argon.blockstack.org:20443/v2/neighbors
Using the DNS `argon-master.blockstack.org` resolves this issue so external neighbors are known to miners.
> Updating bootstrap_node key in the miner config so external neighbors are known

- src/pages/data-storage/storage-guide.md
When calling the put, get, delete methods, refer to the file name without a leading slash.
> Delete leading slash

- src/components/header.tsx
When you go to "Start Building" -> "Documentation", it opens up the home page in a new tab. This adds types to nav items, and adds the optional 'target' option.
> fix: use target _self for documentation link in header

- lib/rehype-image-size.js
- lib/rehype-plugins.js
- package.json
- src/components/feedback.tsx
- src/components/mdx/components/code.tsx
- src/components/mdx/image.tsx
- src/components/mdx/md-contents.tsx
- src/pages/smart-contracts/counter-tutorial.md
- src/pages/smart-contracts/testing-contracts.md
- yarn.lock
- This enables the use of imgix for production deployments (to serve up formats like webp when supported)
- Uses srcset to size images properly on mobile devices
- Fixes a typo in the github url
- I created a small rehype plugin to give us image sizes for local images. This gives us the ability to know the aspect ratio of our images and build it such that the page will never reflow when the image is loaded
> fix: imgix, github typo

- src/pages/stacks-blockchain/testnet-node.md
Fixes #747
When I first opened the markdown file in my editor it had extra line breaks that I do not see in the website, but rendered funny in my markdown preview, so I removed them as part of a217cc2. Otherwise this was a pretty straightforward update to the instructions.
> Simplify rust installation instructions

- src/pages/smart-contracts/principals.md
The `claim-from-faucet` function seems to have two minor bugs in it:
* the `map-set` function should take three arguments, map-name, tuple_A, and tuple_B, but it seems like it was just taking two arguments
* the `err` function seems like it should take a `u1` and not a `1`
> Fix possible bugs in claim-from-faucet

- src/pages/smart-contracts/signing-transactions.md
Resubmitting https://github.com/blockstack/docs/pull/656 since the changes were lost along the way somewhere
> Update transaction signing docs for testnet release (again)

- src/pages/authentication/connect.md
This PR
* adds a connection from the main entry page for Connect (e.g. from github) to the tx signing section with Connect.
> Add reference from main entry of Blockstack connect to signing txs

- src/pages/authentication/building-todo-app.md
This PR 
* fixes the link to the Connect guide on the todo app tutorial
> Fix link to Connect guide

- src/pages/authentication/connect.md
This PR
* replace the current link to the source code of `AuthOptions` from the connect repo to the ux repo.
* updates the optional flags in the properties table of `AuthOptions`
> Fix link to source code of AuthOptions

- src/pages/stacks-blockchain/integrate-stacking.md
This PR fixes a small typo originally pointed out [in Discord](https://discord.com/channels/621759717756370964/750467085720617031/768096526161281024).
> Integrate stacking: fix typo in step 1

- .gitpod.yml
- README.md
In preparation for the docs week, Gitpod could make it easier for folks to get started - there's no need for local setup using Gitpod
No
No
Starting the gitpod by appending `https://gitpod.io/#` to the repo URL
> feat: add gitpod

- src/common/navigation.yaml
- src/pages/mining.md
- src/pages/stacks-blockchain/local-development.md
- src/pages/stacks-blockchain/running-testnet-node.md
1. Super easy mocknet using docker-compose  and https://github.com/blockstack/stacks-local-dev .
2. Syntax updates for existing docker commands (removed comments from commands causing them to fail copypasta)
3. update image used for docker to use `latest` rather than a tagged version (this version is updated when a push to master occurs) - this will prevent lots of updates being required when images are updated. 
Docs being added are a close copy of  https://github.com/blockstack/stacks-local-dev/blob/master/README.md
https://github.com/blockstackpbc/devops/issues/475
> Local mocknet with docker

- src/pages/authentication/connect.md
Small docs changes for Connect usage in React apps.
Changes:
- You need to import from `@blockstack/connect-react` to use hooks and the provider
- Removed the note about bundle sizes, since React is no longer included
> fix: docs for connect-react

- src/pages/stacks-blockchain/running-testnet-node.md
1. Both Release and Debug stacks-node  is being installed which may not be needed. 
2. stacks-node build and execution are included in install section which causes confusion like https://github.com/blockstack/docs/issues/833
> Update running-testnet-node.md to avoid confusion for beginners

- src/pages/mining.md
- src/pages/stacks-blockchain/local-development.md
- src/pages/stacks-blockchain/running-testnet-node.md
To help make the stacks blockchain as easy as possible to run in a variety of ways, this PR adds documentation on how to run the stacks-blockchain Helm chart for the community to easily deploy a stacks node to a local or remote Kubernetes cluster.
Closes issue #848 
For details refer to PR https://github.com/blockstack/stacks-blockchain/pull/2024 (**This referenced PR must be merged before this docs PR**)
No
> docs: add helm docs

- src/pages/mining.md
- src/pages/stacks-blockchain/running-testnet-node.md
Fixes some URLs pointing to the stacks-blockchain helm chart.
> docs: fix URL to stacks helm chart

- src/pages/mining.md
See for details  "Argon config templates should be updated" #619 
There is only one place where the process_exit_at_block_height is missing.
No
No
Nothing special
> fix: add optional config values

- src/pages/authentication/building-todo-app.md
Fixes blockstack/docs#872
Updated the Git hub repo for todo app tutorial .
What has changed: The Github repo for todo app tutorial (https://docs.blockstack.org/authentication/building-todo-app) was updated from 
git clone https://github.com/blockstack/stacks-todos
cd stacks-todos
to git clone https://github.com/blockstack/blockstack-todos
cd blockstack-todos
##What has been fixed
Previously the users were not able to clone the stacks-todo repo since it was not available. With this change, that is fixed.
> fix: Updated the Git repo and success message in todo tutorial

- src/pages/data-storage/storage-guide.md
For details see  `Unclear example in "Reading another user’s unencrypted file"` #508
This PR
* updates links to stacks.js
* updates the file methods as used in stacks.js via `Storage` instead of `UserSession`
* fixes the code snippet for unencrypted files of other users
* fixes #508
> fix: fix getFile for unencrypted files, updates for stacks.js

- src/pages/stacks-blockchain/integrate-stacking.md
See "Missing stacks burn height in Stacking guide" #901 for details.
This PR
* adds start burn ht in the stacking integration guide in step 5.
* fixes #901
> Fix: Missing stacks burn height in Stacking guide #901

- src/pages/smart-contracts/counter-tutorial.md
- src/pages/smart-contracts/overview.md
- src/pages/stacks-blockchain/transactions.md
Fixes blockstack/docs#903
Use the following template to create your pull request
2. What was changed
Updated the "Clarity language Reference" broken URLs in 3 pages. 
1)The link in smart contracts/overview page (https://docs.blockstack.org/smart-contracts/overview)should be redirected to https://docs.blockstack.org/references/language-overview.
2) The link in transactions/#at-block  (https://docs.blockstack.org/stacks-blockchain/transactions) should be redirected to https://docs.blockstack.org/references/language-functions#at-block
3) The link is counter tutorial ( https://docs.blockstack.org/smart-contracts/counter-tutorial) has to be updated to https://docs.blockstack.org/references/language-functions
4. Link to relevant issues and documentation …
> fix: broken Clarity language reference redirection links in few pages  

- src/common/navigation.yaml
- src/pages/smart-contracts/clarity-values-guide.md
- src/pages/smart-contracts/clarity-values.md
A guide for dealing with Clarity values in JS.
#816
> Clarity Values Guide

- next.config.js
- src/pages/authentication/building-todo-app.md
- src/pages/build-an-app.md
- src/pages/smart-contracts/signing-transactions.md
See "Removed connect page is still referenced" #892 for details.
This PR 
* adds a permanent link for authentication/connect to the stacks.js reference on github (until there is a better place)
* replaces connect content with stacks.js content
* fixes #892
> fix: authentication/connect was removed

- src/pages/stacks-blockchain/mining.md
For details refer to issue #917 
This PR 
* replaces "Stacks Tokens" with "STX" in the list where only "STX" is used otherwise.
* fixes #917
> fix: use STX consistently in coinbase rewards #917

- src/pages/stacks-blockchain/integrate-stacking.md
- src/pages/stacks-blockchain/sending-tokens.md
- src/pages/stacks-blockchain/transactions.md
`StacksTestnet` is defined in `@stacks/network`, not in `@stacks/transactions`. 
This PR replaces wrong imports with the correct ones.
> fix: use stacks/network for Testnet

- src/pages/mining.md
This is a small change to point miners to a different testnet BTC faucet. This is required for Xenon, because we'll no longer be using our own testnet.
Don't merge until Xenon is ready!
> feat: update btc faucet location

- src/pages/smart-contracts/testing-contracts.md
Contract ids should not be used in the documentation. Instead use contract identifier.
This PR
* replaces contract id with contract identifier (1 place)
* replaces wrong use of contract identifier with contract name (1 place)
* fixes #896
> fix: replace contract id with contract identifier #896

- src/pages/storage-hubs/digital-ocean-deploy.md
I was going through the tutorial to deploy Gaia to Digital Ocean and noticed some weird formatting which is in the screenshot below.
I was thinking it should look like below. So, I modified the page
No
No 
No
> Fix Formatting in Deploy on DigitalOcean page

- src/pages/understand-stacks/overview.md
this is a leftover stemming from a merge conflict
> docs: remove API from top section in overview

- src/pages/start-mining.md
This PR changes the bootstrap node from testnet-miner.blockstack.org to xenon.blockstack.org
> use xenon.blockstack.org as bootstrap node

- .github/workflows/stylecheck-prs.yml
- .vale/vale.ini
There is a Vale action and config files in the docs repo, but we don't have a check that runs on PRs. This change adds a Github action to compare changed files to the styleguide and point out suggestions/errors.
irt https://github.com/blockstackpbc/devops/issues/527
this also considers a known Vale issue: https://github.com/errata-ai/vale-action/issues/27
> feat: add github action for vale check

- src/pages/understand-stacks/command-line-interface.md
This PR updates the recommended transaction fee rate for testnet from 1 to 200 in the CLI guide.
Fixes: https://github.com/blockstack/docs/issues/993
> fix: testnet fee rate in CLI guide

- next.config.js
- public/images/pages/mainnet-sm.svg
- public/images/pages/mainnet.svg
- src/common/navigation.yaml
- src/components/custom-blocks/page-reference.tsx
- src/pages/references/stacks-node-configuration.md
- src/pages/start-mining/mainnet.md
- src/pages/start-mining/testnet.md
- src/pages/understand-stacks/running-mainnet-node.md
* Adds instructions for running a mainnet node
* Adds instructions for running a mainnet miner
* Separates running a mainnet and testnet miner onto two separate pages
* Updates testnet miner redirect
* Adds new icons for mainnet pages
* Updates stacks-node configuration references
Closes https://github.com/blockstackpbc/devops/issues/545
> Mainnet docs and changes

- src/pages/understand-stacks/technical-specs.md
> docs: remove overlap note for prepare phase

- src/pages/start-mining/mainnet.md
- src/pages/start-mining/testnet.md
- src/pages/understand-stacks/running-mainnet-node.md
- src/pages/understand-stacks/running-testnet-node.md
This PR is updating references to BLOCKSTACK_DEBUG - which is now STACKS_LOG_DEBUG.
> rename BLOCKSTACK_DEBUG to STACKS_LOG_DEBUG

- src/pages/build-apps/guides/transaction-signing.md
I saw a bug in Discord, and saw that the dev was using an out-of-date API for transaction signing with contract calls. I went to point them to the docs... but then the docs were out of date. Their code can work (I'm pretty sure?), but the API is much more robust right now, and supports all `ClarityValue`s from `@stacks/transactions`.
I must have forgotten to update the docs, and I obviously missed this when reviewing Mark's recent PR.
I've also added a sample Clarity contract, which I think helps explain the whole flow a little better.
> fix: updated docs for transaction signing with connect

- src/pages/build-apps/guides/authentication.md
- src/pages/build-apps/guides/data-storage.md
- src/pages/build-apps/guides/transaction-signing.md
A few small changes related to transaction signing. Lots more to improve here but it's better than nothing!
- Update some links that pointed to https://blockstack.org/wallet to https://hiro.so/wallet/install-web.
- Add a notice in the installation section that you have to use a Connect beta (hopefully resolving that soon, just don't want devs to go through the wrong flow)
- Add docs about specifying the `network` option through Connect
- Add docs for getting the current user's STX address
- Updated `onFinish` docs - it now includes a `stacksTransaction` property.
> fix: docs for specifying network when transaction signing

- .github/workflows/stylecheck-prs.yml
- src/pages/build-apps/guides/transaction-signing.md
- vale.ini
The `vale-action` was failing due to some misconfiguration. We don't need to have a remotely-hosted `.vale.ini` file - that's only needed if the file is not available in your repo. The `.vale.ini` file also had an incorrect `StylesPath`, which caused the pr to fail.
> fix: vale.ini location

- src/pages/write-smart-contracts/hello-world-tutorial.md
This PR
* changes the last part of the hello world tutorial to clarify where to look for the tx result.
The user should be directed to the explorer to lookup the tx id
> Clarify where the output of a tx appears

- src/pages/build-apps/guides/transaction-signing.md
Mainly just a better named NPM tag, which we have talked about. Now it's ready.
> fix: update guidance to use 'canary' npm tag for tx signing

- src/pages/understand-stacks/managing-accounts.md
`Step 2: Generating an account` does not work because
```
import fetch from 'cross-fetch';
^^^^^^
SyntaxError: Cannot use import statement outside a module
```
> fix: "Generating an account" code sample does not work

- src/pages/understand-stacks/transactions.md
This PR
* updates the section about post-conditions
The post-conditions is always about the original owner of the asset. The literal is only applicable to fungible tokens.
@agraebe
> Clarify the section about post-conditions

- src/pages/write-smart-contracts/counter-tutorial.md
`get-counter` function was defined as `public`, which didn't make sense. It should be `read-only`.
> Fix get-counter function type in the counter tutorial

- src/pages/404.md
- src/pages/index.md
- src/pages/understand-stacks/running-mainnet-node.md
- src/pages/understand-stacks/running-testnet-node.md
- src/pages/understand-stacks/stacking.md
Fixes the links from setting up a mainnet/testnet node to the mainnet/testnet mining pages.
> docs: fix url to mining pages

- src/pages/understand-stacks/command-line-interface.md
See [Network Selection Issue](https://github.com/blockstack/docs/issues/1115).
> Issue 1115.

- src/common/navigation.yaml
This PR fixes the broken links in the Ecosystem left nav (#1000).  Please review the preview build and ensure that this is the expected look and feel - this change brings the Ecosystem section in line with the other sections so that the links are not always shown in the sidebar.
> fix: fixed links in sidebar nav for ecosystem section

- src/components/layouts/base-layout.tsx
Fix content butting up against the scrollbar when the window is collapsed but hasn't yet hit the mobile breakpoint.  This resolves #774.
> fix: left padding on content section

- mlc_config.json
Updated the link checking configuration to use the updated domain name of the documentation site
> chore: updated link checking to point at the docs.stacks.co domain

- next.config.js
- src/common/hooks/use-fathom.ts
Fathom tracking was broken for the site, after talking to Thomas I updated the domain it is pointed at and also established a new dashboard on Fathom that represents the correct domain.
> fix: fathom analytics

- src/common/navigation.yaml
Point the `connect` link to the `blockstack/connect` repository README
> fix: updated external link to connect repo

- src/pages/references/stacks-node-configuration.md
- src/pages/start-mining/mainnet.md
- src/pages/start-mining/testnet.md
Updates the testnet and mainnet miner pages to make better use of the new example configs which will become available once this PR is merged: https://github.com/blockstack/stacks-blockchain/pull/2652
> docs: use new example configs to simplify docs

- src/pages/write-smart-contracts/testing-contracts.md
Latest `'@blockstack/clarity'` uses `method` not `function`
> fix: incorrect prop argument name

- src/common/navigation.yaml
In order to highlight community content, I'm adding a link to the open source Awesome Stacks page in the Ecosystem section. We're encouraging community members to populate that page with projects that are excellent examples of what the Stacks chain is capable of.  Awesome Stacks is maintained by @friedger.
This PR closes #987 .
> feat: add link to Awesome Stacks to highlight community content

- src/pages/write-smart-contracts/hello-world-tutorial.md
A dash is missing in echo number function name
@pgray-hiro
> fix: misspelled function name in code sample

- src/pages/build-apps/examples/heystack.md
- src/pages/write-smart-contracts/clarinet.md
This PR adds embedded videos to the Clarinet and Heystack pages from the presentations during the Accelerator Clarity week.
> docs: add Accelerator videos to documentation

- .vale/styles/Google/Colons.yml
- .vale/styles/Google/HeadingColons.yml
- .vale/styles/Google/Headings.yml
After talking with @wileyj about our capitalization rules regarding text in headings after colons, I read the Google Developers Guide to Style closely and determined that our style enforcer is not matching the recommendation from Google. Specifically, the guide says:
"In document titles and headings, use sentence case. That is, capitalize only the first word in the title, _the first word in a subheading after a colon_, and any proper nouns or other terms that are always capitalized a certain way."
(emphasis mine)
This PR updates our style rules to throw a warning on an uncapitalized word immediately following a colon in a heading.
> feat: add capitalization rule for colons in headings

- .vale.ini
- .vale/styles/Vocab/docs/accept.txt
This is a re-opening of a PR that was having weird merge conflict problems. It adds two words to the accept list and changes the default level for the style checker to `warning`.
> chore: add accepted words and de-fang the style checker

- src/_data/clarity-reference.json
Reverts blockstack/docs#1222 - Change needs to be made in `blockstack/stacks-blockchain`
> Revert "Update clarity-reference.json"

- src/pages/write-smart-contracts/clarinet.md
This PR removes the description how to install clarinet because it fails:
```
cargo install clarinet --locked
Updating crates.io index
error: could not find `clarinet` in registry `https://github.com/rust-lang/crates.io-index` with version `*`
```
> Update clarinet installation method

- src/pages/write-smart-contracts/clarinet.md
- src/pages/write-smart-contracts/counter-tutorial.md
- src/pages/write-smart-contracts/hello-world-tutorial.md
- src/pages/write-smart-contracts/overview.md
This PR adds links to the VSCode plugin for Clarity to the tutorials and the Clarity overview page.
Closes #1209
> docs: add VSCode plugin links

- src/pages/build-apps/guides/authentication.md
Change: Renamed `finished` method to `onFinish`
Motivation: The appropriate name of the post-authentication callback seems to be `onFinish`, not `finished` based on the code here: https://github.com/blockstack/connect/blob/main/packages/connect/src/auth.ts. I am proposing this update because my code editor complained about providing the improper function property of `AuthOptions` as I was following the instructions in the [`Authentication` module of the Stacks docs](https://docs.stacks.co/build-apps/guides/authentication).
> Replace finished method with onFinish

- .github/workflows/main.yml
- src/pages/write-smart-contracts/clarinet.md
This PR updates the actions configuration to run the code_quality check on PR, rather than on push. This should resolve the problem of the check not occurring when community members open PRs.
> fix: code_quality not firing on community PRs

- src/components/header.tsx
The Discord invite link in the header of https://docs.stacks.co/ site was wrong.
In file: `src/components/header.tsx`, Discord link was changed from: 'https://discord.com/invite/6PcCMU', to: 'https://discord.gg/zrvWsQC'. I've tested a new link during my sign-up to the server. The new link comes from the `https://community.stacks.org/` website.
No issues were created
> Fix Discord invite link in header

- src/pages/understand-stacks/sending-tokens.md
- src/pages/write-smart-contracts/counter-tutorial.md
This PR fixes 2 broken links in the Counter tutorial. Additional a linting error is fixed on a different page.
Closes #1241
> Fix broken links in Counter tutorial

- src/pages/build-apps/examples/public-registry.md
- src/pages/build-apps/examples/todos.md
- src/pages/build-apps/guides/authentication.md
- src/pages/build-apps/guides/data-storage.md
- src/pages/build-apps/overview.md
This PR fixes an annoying grammar error with the "Todos" tutorial. The correct English spelling for this word is "To-dos", hyphenated to denote that it is actually two words smashed together. This should alleviate any confusion for multilingual users.
Note, this change does not change the code samples, which would need to be updated in the various repos. That change will be coordinated with the corresponding change in the example repositories.
Closes #1191
> fix: todo -> to-do

- src/pages/understand-stacks/running-mainnet-node.md
- src/pages/understand-stacks/running-testnet-node.md
- src/pages/understand-stacks/sending-tokens.md
Update the mainnet docs to reflect the work done to run an api node. 
Essentially this is a copypasta of the api doc, with all references to postgres/api removed since we're only covering the stacks blockchain instance. 
of note: i did remove the part about running the container on a specific network to make it a little easier to run. for the API, this network is required for DNS - but for **only** the stacks blockchain, this is not essential. 
https://github.com/blockstack/docs/issues/1188
> running a mainnet node (modelled after running api node)

- src/pages/understand-stacks/microblocks.md
This PR updates the microblocks documentation with information from Aaron in the microblocks discussion in #1232. This is an initial attempt to provide a set of best-practices for how to display pending state represented by microblocks in different kinds of applications.
Closes #1232.
> docs: Update microblocks doc based on internal discussions

- src/pages/build-apps/guides/data-storage.md
when a user copies the example JSON payloads, there is an error just from a missing comma
> Add Commas For Example JSON

- src/pages/build-apps/examples/todos.md
The name used in the docs doesn't match the code so I fixed it. Maybe this used to be called `finished`, then was renamed but the renaming was not reflected in the docs :)
> Reflect correct name in the docs

- src/pages/ecosystem/contributing.md
As a new contributor, I didn't know about Conventional Commits requirements until creating a pull request. I think it is a bit too late as I had to change my commits names. To avoid that in the future for other contributors, I suggest adding this requirement to the "Contributing" docs page. If you think It should be organized as a separate section (or in any other way than I did it) please provide feedback.
A new section in "Tips and tricks" was added.
No relevant issue was created.
> Add information about conventional commits to contribution docs

- src/pages/understand-stacks/running-mainnet-node.md
Following the steps of the documentation to run a mainnet node results in `Error: No such container: stacks-blockchain`
The problem is that the docker image crashes without notifying the user due to `-d` option. The crash is caused by a wrong path to the config file.
This PR fixes the path.
Thank you to @d1gitalflow for finding the problem and notifying.
> Fix path to config file

- src/pages/references/language-types.md
The Clarity type `tuple` is explained by the expression `tuple`. This PR improves the definition by replacing the expression `tuple` with a full descriptive expression and adds a reference to records.
It was agreed that _records_ are the most correct programming language expression: https://github.com/clarity-lang/reference/issues/5#issuecomment-657152788
> fix: improve type definition of tuple

- src/components/feedback.tsx
The link of "Edit this page on Github" that appear at the bottom of most pages is broken on most cases.
For example, it works here: 
https://docs.stacks.co/ 
when it points to:
https://github.com/blockstack/docs/edit/master/src/pages/index.md
But not here:
https://docs.stacks.co/understand-stacks/overview
when it points to:
https://github.com/blockstack/docs/edit/master/src/pages/understand-stacks/overview.md
Because it should be instead:
https://github.com/blockstack/docs/edit/master/src/pages/understand-stacks/overview/index.md
This PR fixes the issue by changed the generated URL.
The first link only works because this file appears duplicated:
https://github.com/blockstack/docs/blob/master/src/pages/index.md
and
https://github.com/blockstack/docs/blob/master/src/pages/index/index.md …
> fixed edit-this-page-on-github

- src/pages/en/understand-stacks/mining.md
This PR removes two paragraphs from the mining pages that referenced 'sunset'.
> remove sunset reference from mining

- src/common/constants_that_require_translations.ts
End of file requirement so `yarn lint` can run correctly.
> end of file requirement

- src/components/toc.tsx
I am currently learning Clarity through the Miami Clarity Camp and when I came across the functions section of the docs, I noticed some of the links weren't working. I saw it was an open issue so I decided to work on it. At first, I wanted to fix where the ids are being generated since that is probably where the extras '-' are coming from, but I was not able to find the location. So I decided a quick fix would just be updating where the page links are being generated. I only made changes to the file listed below on line 106. Before the function names get slugified, I made it so that it checks first for a '-' sign since subtract has two '--', then checks for other special characters and prepends the necessary '-' characters to the slugified name if necessary.
src/components/toc.tsx
```
106 …
```
> fix: Clarity functions reference autogenerates with bugs #1306

- docs/write-smart-contracts/clarity-language/language-functions.md
I am learning clarity; attending clarity bootcamp 4 now. So, last a week or so I am on this document everyday.
I came across a few errors on the document, and I would like to add more examples, while I am learning.
While experimenting with **/ (divide)**, I realized that it is not an "integer division". According to wolfram and wikipedia, in integer division, the floor function is applied to the result.
https://mathworld.wolfram.com/IntegerDivision.html
https://en.wikipedia.org/wiki/Division_(mathematics)#Of_integers
Clarity doesn't apply the floor function, it simply returns the integer part of the division, So I changed the description of the **/ (divide)** accordingly.
And I added more examples to 4 Arithmetic Operations.
> Description of divide and more examples

- docs/write-smart-contracts/clarity-language/language-functions.md
- Log2 fails on 'Zero' 
- There is no rounding, but striping out the decimal point from result
- Indentation of the output in the example, for readability
> log2 description and examples

- docs/write-smart-contracts/clarity-language/language-functions.md
This PR adds information that the sec256k1-verify function throws an unchecked error if the input arguments have a wrong buffer length.
> Add uncheck error information for secp256k1-verify

- docs/write-smart-contracts/clarity-language/language-functions.md
Update output type for `as-max-len?` and document corner cases for `pow`.
> recent updates from stacks-blockchain

- docs/clarity/index.md
> fix: minor typo in Clarity doc

- nakamoto-upgrade/running-a-signer.md
Change the guidance around encoding tools to use local method:
```bash
python3 -m venv .venv
source .venv/bin/activate
pip3 install base58
sudo bash -c 'cat <<EOF> ./encode.py
from sys import argv
import base58
print(base58.b58encode(argv[1]).decode("utf-8"))
EOF'
python3 ./encode.py PRIVATE_KEY
```
> Fix nit around online tooling.

- stacks-in-depth/nodes-and-miners/mine-testnet-stacks-tokens.md
`2.4.0.1.0` had an upstream dependency update that requires a small change to running stacks-node with the `--config` arg:
previously: `stacks-node --config=/path/to/Config.toml` was valid. 
with the update, the above no longer works and must be: `stacks-node --config /path/to/Config.toml`
note the missing `=`
> Removing equals from --config (pico-args upstream update)

- nakamoto-upgrade/signing-and-stacking/running-a-signer.md
- nakamoto-upgrade/signing-and-stacking/stacking-flow.md
- stacks-in-depth/nodes-and-miners/run-a-node-with-docker.md
In testing, 250GB *is ok* - but on a Debian server based system (i.e. not a lot of extra packages installed), the chainstate + the os takes around 220GB. 
the chainstate itself is around 190GB today. 
updating to 350GB should be considered the new minimum for 6-12 months of chain growth.
> Update storage reqs to 350GB and other fixes

- nakamoto-upgrade/nakamoto-rollout-plan/nakamoto-for-exchanges.md
- nakamoto-upgrade/nakamoto/nakamoto-stacking-quickstart.md
`api.nakamoto.testnet` -> `api.testnet`
> update testnet link

- stacks-in-depth/nodes-and-miners/mine-mainnet-stacks-tokens.md
- stacks-in-depth/nodes-and-miners/stacks-node-configuration.md
`bootstrap_nodes` config setting in the mining docs was still set to use the old values. 
this updates to use the current default values
> Chore: update bootstrap_nodes config to use current default values
